---
title: "Introduction and resources"
author: "Haeun Lee"
date: "2026-11-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
R.version.string

# install Bioconductor and check version
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("3.15")
BiocManager::version()
BiocManager::install(version = "3.15")

install.packages("BiocInstaller", repos="http://bioconductor.org/packages/3.15/bioc")
library(BiocInstaller)
biocLite()
biocLite(c("name of package"))

install.packages(c("devtools", "rafalib", "RColorBrewer", "gplots", "UsingR", "class", "caret"))
library(devtools)
library(rafalib)
library(RColorBrewer)
library(gplots)
library(UsingR)
library(class)
library(caret)

install.packages("Matrix")

# install Bioconductor packages
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
BiocManager::install(c("genefilter","geneplotter"))

# load installed packages
library(BSgenome.Hsapiens.UCSC.hg19)
library(genefilter)
library(geneplotter)

# get help through the documentation
help.start()
?mean
help(mean)
help(package="genefilter")

# inspect objects, classes and methods
library(Biobase)    # load one of the core Bioconductor packages
?ExpressionSet
?"ExpressionSet-class"
methods(class = ExpressionSet)

# inspect the source code for functions and methods
read.csv
plotMA
showMethods("plotMA")
getMethod("plotMA","data.frame")

# vignettes teach you how to use various functions in a package
vignette(package="Biobase")
vignette("ExpressionSetIntroduction")
browseVignettes(package="Biobase")

# report key details about your R session
sessionInfo()
```

